name: FetchTweetsAndReply

on:
  schedule:
    # 10,13,16,19,22 IST → converted to UTC: 04:30,07:30,10:30,13:30,16:30
    - cron: '30 4,7,10,13,16 * * *'
  workflow_dispatch: {}  # Manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy requests apify-client

      - name: Run fetch and immediate reply
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: |
          python apyfi_fetch_reply.py
