name: Fetch Latest Tweets

on:
  workflow_dispatch:  # manual trigger for now

jobs:
  fetch-tweets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tweet fetcher
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          TWITTER_USERNAME: elonmusk
        run: python apyfi_fetch.py
