name: Fetch Latest Tweet

on:
  workflow_dispatch:

jobs:
  fetch_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install apify-client

      - name: Run tweet fetcher
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
        run: python apyfi_fetch.py
