name: Continuous News Bot

on:
  # Scheduled automated run every hour from 9 AM to 1 AM IST (3-19 UTC)
  schedule:
    - cron: '0 3-19 * * *'
  # Manual trigger
  workflow_dispatch:
    inputs:
      mode:
        description: 'Select mode: auto = full bot, manual = fetch & post one category'
        required: true
        default: auto

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Continuous News Bot
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: |
          python continuous_news_bot_with_manual.py <<< "${{ github.event.inputs.mode }}"
