name: Controversy Bot

on:
  # Auto hourly run for posting
  schedule:
    - cron: '0 * * * *'  # every hour at minute 0
  # Manual trigger from GitHub UI
  workflow_dispatch:
    inputs:
      category:
        description: 'Optional: category for manual fetch (bjp/congress/countries/others)'
        required: false
        default: ''

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Controversy Bot
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Manual trigger
            if [ -z "${{ github.event.inputs.category }}" ]; then
              echo "🟡 Manual fetch with default category: bjp"
              python bot2.py manual
            else
              echo "🟡 Manual fetch for category: ${{ github.event.inputs.category }}"
              python bot2.py manual ${{ github.event.inputs.category }}
            fi
          else
            # Auto hourly run
            python bot2.py
